/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuiviCommandeRouteImport } from './routes/suivi-commande'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PolitiqueCookiesRouteImport } from './routes/politique-cookies'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MontresHommeRouteImport } from './routes/montres-homme'
import { Route as MontresFemmeRouteImport } from './routes/montres-femme'
import { Route as MontresEnfantRouteImport } from './routes/montres-enfant'
import { Route as MontresCoupleRouteImport } from './routes/montres-couple'
import { Route as MontresConnecteesRouteImport } from './routes/montres-connectees'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MarquesRouteImport } from './routes/marques'
import { Route as LivraisonRetoursRouteImport } from './routes/livraison-retours'
import { Route as GarantieRouteImport } from './routes/garantie'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConditionsGeneralesVenteRouteImport } from './routes/conditions-generales-vente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MontresIndexRouteImport } from './routes/montres.index'
import { Route as CommandeIndexRouteImport } from './routes/commande.index'
import { Route as MontresSlugRouteImport } from './routes/montres.$slug'
import { Route as CommandeConfirmationRouteImport } from './routes/commande.confirmation'
import { Route as CollectionsCoffretsCadeauxRouteImport } from './routes/collections.coffrets-cadeaux'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'

const SuiviCommandeRoute = SuiviCommandeRouteImport.update({
  id: '/suivi-commande',
  path: '/suivi-commande',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueCookiesRoute = PolitiqueCookiesRouteImport.update({
  id: '/politique-cookies',
  path: '/politique-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresHommeRoute = MontresHommeRouteImport.update({
  id: '/montres-homme',
  path: '/montres-homme',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresFemmeRoute = MontresFemmeRouteImport.update({
  id: '/montres-femme',
  path: '/montres-femme',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresEnfantRoute = MontresEnfantRouteImport.update({
  id: '/montres-enfant',
  path: '/montres-enfant',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresCoupleRoute = MontresCoupleRouteImport.update({
  id: '/montres-couple',
  path: '/montres-couple',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresConnecteesRoute = MontresConnecteesRouteImport.update({
  id: '/montres-connectees',
  path: '/montres-connectees',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MarquesRoute = MarquesRouteImport.update({
  id: '/marques',
  path: '/marques',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonRetoursRoute = LivraisonRetoursRouteImport.update({
  id: '/livraison-retours',
  path: '/livraison-retours',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantieRoute = GarantieRouteImport.update({
  id: '/garantie',
  path: '/garantie',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesVenteRoute =
  ConditionsGeneralesVenteRouteImport.update({
    id: '/conditions-generales-vente',
    path: '/conditions-generales-vente',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresIndexRoute = MontresIndexRouteImport.update({
  id: '/montres/',
  path: '/montres/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeIndexRoute = CommandeIndexRouteImport.update({
  id: '/commande/',
  path: '/commande/',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresSlugRoute = MontresSlugRouteImport.update({
  id: '/montres/$slug',
  path: '/montres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeConfirmationRoute = CommandeConfirmationRouteImport.update({
  id: '/commande/confirmation',
  path: '/commande/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCoffretsCadeauxRoute =
  CollectionsCoffretsCadeauxRouteImport.update({
    id: '/collections/coffrets-cadeaux',
    path: '/collections/coffrets-cadeaux',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditions-generales-vente': typeof ConditionsGeneralesVenteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/garantie': typeof GarantieRoute
  '/livraison-retours': typeof LivraisonRetoursRoute
  '/marques': typeof MarquesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/montres-connectees': typeof MontresConnecteesRoute
  '/montres-couple': typeof MontresCoupleRoute
  '/montres-enfant': typeof MontresEnfantRoute
  '/montres-femme': typeof MontresFemmeRoute
  '/montres-homme': typeof MontresHommeRoute
  '/panier': typeof PanierRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/politique-cookies': typeof PolitiqueCookiesRoute
  '/promotions': typeof PromotionsRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/coffrets-cadeaux': typeof CollectionsCoffretsCadeauxRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/montres/$slug': typeof MontresSlugRoute
  '/commande/': typeof CommandeIndexRoute
  '/montres/': typeof MontresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions-generales-vente': typeof ConditionsGeneralesVenteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/garantie': typeof GarantieRoute
  '/livraison-retours': typeof LivraisonRetoursRoute
  '/marques': typeof MarquesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/montres-connectees': typeof MontresConnecteesRoute
  '/montres-couple': typeof MontresCoupleRoute
  '/montres-enfant': typeof MontresEnfantRoute
  '/montres-femme': typeof MontresFemmeRoute
  '/montres-homme': typeof MontresHommeRoute
  '/panier': typeof PanierRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/politique-cookies': typeof PolitiqueCookiesRoute
  '/promotions': typeof PromotionsRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/coffrets-cadeaux': typeof CollectionsCoffretsCadeauxRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/montres/$slug': typeof MontresSlugRoute
  '/commande': typeof CommandeIndexRoute
  '/montres': typeof MontresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conditions-generales-vente': typeof ConditionsGeneralesVenteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/garantie': typeof GarantieRoute
  '/livraison-retours': typeof LivraisonRetoursRoute
  '/marques': typeof MarquesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/montres-connectees': typeof MontresConnecteesRoute
  '/montres-couple': typeof MontresCoupleRoute
  '/montres-enfant': typeof MontresEnfantRoute
  '/montres-femme': typeof MontresFemmeRoute
  '/montres-homme': typeof MontresHommeRoute
  '/panier': typeof PanierRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/politique-cookies': typeof PolitiqueCookiesRoute
  '/promotions': typeof PromotionsRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/coffrets-cadeaux': typeof CollectionsCoffretsCadeauxRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/montres/$slug': typeof MontresSlugRoute
  '/commande/': typeof CommandeIndexRoute
  '/montres/': typeof MontresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conditions-generales-vente'
    | '/contact'
    | '/faq'
    | '/favoris'
    | '/garantie'
    | '/livraison-retours'
    | '/marques'
    | '/mentions-legales'
    | '/montres-connectees'
    | '/montres-couple'
    | '/montres-enfant'
    | '/montres-femme'
    | '/montres-homme'
    | '/panier'
    | '/politique-confidentialite'
    | '/politique-cookies'
    | '/promotions'
    | '/suivi-commande'
    | '/categories/$slug'
    | '/collections/coffrets-cadeaux'
    | '/commande/confirmation'
    | '/montres/$slug'
    | '/commande/'
    | '/montres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conditions-generales-vente'
    | '/contact'
    | '/faq'
    | '/favoris'
    | '/garantie'
    | '/livraison-retours'
    | '/marques'
    | '/mentions-legales'
    | '/montres-connectees'
    | '/montres-couple'
    | '/montres-enfant'
    | '/montres-femme'
    | '/montres-homme'
    | '/panier'
    | '/politique-confidentialite'
    | '/politique-cookies'
    | '/promotions'
    | '/suivi-commande'
    | '/categories/$slug'
    | '/collections/coffrets-cadeaux'
    | '/commande/confirmation'
    | '/montres/$slug'
    | '/commande'
    | '/montres'
  id:
    | '__root__'
    | '/'
    | '/conditions-generales-vente'
    | '/contact'
    | '/faq'
    | '/favoris'
    | '/garantie'
    | '/livraison-retours'
    | '/marques'
    | '/mentions-legales'
    | '/montres-connectees'
    | '/montres-couple'
    | '/montres-enfant'
    | '/montres-femme'
    | '/montres-homme'
    | '/panier'
    | '/politique-confidentialite'
    | '/politique-cookies'
    | '/promotions'
    | '/suivi-commande'
    | '/categories/$slug'
    | '/collections/coffrets-cadeaux'
    | '/commande/confirmation'
    | '/montres/$slug'
    | '/commande/'
    | '/montres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionsGeneralesVenteRoute: typeof ConditionsGeneralesVenteRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FavorisRoute: typeof FavorisRoute
  GarantieRoute: typeof GarantieRoute
  LivraisonRetoursRoute: typeof LivraisonRetoursRoute
  MarquesRoute: typeof MarquesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MontresConnecteesRoute: typeof MontresConnecteesRoute
  MontresCoupleRoute: typeof MontresCoupleRoute
  MontresEnfantRoute: typeof MontresEnfantRoute
  MontresFemmeRoute: typeof MontresFemmeRoute
  MontresHommeRoute: typeof MontresHommeRoute
  PanierRoute: typeof PanierRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  PolitiqueCookiesRoute: typeof PolitiqueCookiesRoute
  PromotionsRoute: typeof PromotionsRoute
  SuiviCommandeRoute: typeof SuiviCommandeRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CollectionsCoffretsCadeauxRoute: typeof CollectionsCoffretsCadeauxRoute
  CommandeConfirmationRoute: typeof CommandeConfirmationRoute
  MontresSlugRoute: typeof MontresSlugRoute
  CommandeIndexRoute: typeof CommandeIndexRoute
  MontresIndexRoute: typeof MontresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suivi-commande': {
      id: '/suivi-commande'
      path: '/suivi-commande'
      fullPath: '/suivi-commande'
      preLoaderRoute: typeof SuiviCommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-cookies': {
      id: '/politique-cookies'
      path: '/politique-cookies'
      fullPath: '/politique-cookies'
      preLoaderRoute: typeof PolitiqueCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres-homme': {
      id: '/montres-homme'
      path: '/montres-homme'
      fullPath: '/montres-homme'
      preLoaderRoute: typeof MontresHommeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres-femme': {
      id: '/montres-femme'
      path: '/montres-femme'
      fullPath: '/montres-femme'
      preLoaderRoute: typeof MontresFemmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres-enfant': {
      id: '/montres-enfant'
      path: '/montres-enfant'
      fullPath: '/montres-enfant'
      preLoaderRoute: typeof MontresEnfantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres-couple': {
      id: '/montres-couple'
      path: '/montres-couple'
      fullPath: '/montres-couple'
      preLoaderRoute: typeof MontresCoupleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres-connectees': {
      id: '/montres-connectees'
      path: '/montres-connectees'
      fullPath: '/montres-connectees'
      preLoaderRoute: typeof MontresConnecteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marques': {
      id: '/marques'
      path: '/marques'
      fullPath: '/marques'
      preLoaderRoute: typeof MarquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison-retours': {
      id: '/livraison-retours'
      path: '/livraison-retours'
      fullPath: '/livraison-retours'
      preLoaderRoute: typeof LivraisonRetoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantie': {
      id: '/garantie'
      path: '/garantie'
      fullPath: '/garantie'
      preLoaderRoute: typeof GarantieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales-vente': {
      id: '/conditions-generales-vente'
      path: '/conditions-generales-vente'
      fullPath: '/conditions-generales-vente'
      preLoaderRoute: typeof ConditionsGeneralesVenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres/': {
      id: '/montres/'
      path: '/montres'
      fullPath: '/montres/'
      preLoaderRoute: typeof MontresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/': {
      id: '/commande/'
      path: '/commande'
      fullPath: '/commande/'
      preLoaderRoute: typeof CommandeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres/$slug': {
      id: '/montres/$slug'
      path: '/montres/$slug'
      fullPath: '/montres/$slug'
      preLoaderRoute: typeof MontresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/confirmation': {
      id: '/commande/confirmation'
      path: '/commande/confirmation'
      fullPath: '/commande/confirmation'
      preLoaderRoute: typeof CommandeConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/coffrets-cadeaux': {
      id: '/collections/coffrets-cadeaux'
      path: '/collections/coffrets-cadeaux'
      fullPath: '/collections/coffrets-cadeaux'
      preLoaderRoute: typeof CollectionsCoffretsCadeauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionsGeneralesVenteRoute: ConditionsGeneralesVenteRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FavorisRoute: FavorisRoute,
  GarantieRoute: GarantieRoute,
  LivraisonRetoursRoute: LivraisonRetoursRoute,
  MarquesRoute: MarquesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MontresConnecteesRoute: MontresConnecteesRoute,
  MontresCoupleRoute: MontresCoupleRoute,
  MontresEnfantRoute: MontresEnfantRoute,
  MontresFemmeRoute: MontresFemmeRoute,
  MontresHommeRoute: MontresHommeRoute,
  PanierRoute: PanierRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  PolitiqueCookiesRoute: PolitiqueCookiesRoute,
  PromotionsRoute: PromotionsRoute,
  SuiviCommandeRoute: SuiviCommandeRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CollectionsCoffretsCadeauxRoute: CollectionsCoffretsCadeauxRoute,
  CommandeConfirmationRoute: CommandeConfirmationRoute,
  MontresSlugRoute: MontresSlugRoute,
  CommandeIndexRoute: CommandeIndexRoute,
  MontresIndexRoute: MontresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
