/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuiviCommandeRouteImport } from './routes/suivi-commande'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MontresHommeRouteImport } from './routes/montres-homme'
import { Route as MontresFemmeRouteImport } from './routes/montres-femme'
import { Route as MontresEnfantRouteImport } from './routes/montres-enfant'
import { Route as MontresCoupleRouteImport } from './routes/montres-couple'
import { Route as MontresConnecteesRouteImport } from './routes/montres-connectees'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConditionsGeneralesVenteRouteImport } from './routes/conditions-generales-vente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MontresIndexRouteImport } from './routes/montres.index'
import { Route as MontresSlugRouteImport } from './routes/montres.$slug'
import { Route as CollectionsCoffretsCadeauxRouteImport } from './routes/collections.coffrets-cadeaux'

const SuiviCommandeRoute = SuiviCommandeRouteImport.update({
  id: '/suivi-commande',
  path: '/suivi-commande',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresHommeRoute = MontresHommeRouteImport.update({
  id: '/montres-homme',
  path: '/montres-homme',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresFemmeRoute = MontresFemmeRouteImport.update({
  id: '/montres-femme',
  path: '/montres-femme',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresEnfantRoute = MontresEnfantRouteImport.update({
  id: '/montres-enfant',
  path: '/montres-enfant',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresCoupleRoute = MontresCoupleRouteImport.update({
  id: '/montres-couple',
  path: '/montres-couple',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresConnecteesRoute = MontresConnecteesRouteImport.update({
  id: '/montres-connectees',
  path: '/montres-connectees',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesVenteRoute =
  ConditionsGeneralesVenteRouteImport.update({
    id: '/conditions-generales-vente',
    path: '/conditions-generales-vente',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresIndexRoute = MontresIndexRouteImport.update({
  id: '/montres/',
  path: '/montres/',
  getParentRoute: () => rootRouteImport,
} as any)
const MontresSlugRoute = MontresSlugRouteImport.update({
  id: '/montres/$slug',
  path: '/montres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCoffretsCadeauxRoute =
  CollectionsCoffretsCadeauxRouteImport.update({
    id: '/collections/coffrets-cadeaux',
    path: '/collections/coffrets-cadeaux',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditions-generales-vente': typeof ConditionsGeneralesVenteRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/montres-connectees': typeof MontresConnecteesRoute
  '/montres-couple': typeof MontresCoupleRoute
  '/montres-enfant': typeof MontresEnfantRoute
  '/montres-femme': typeof MontresFemmeRoute
  '/montres-homme': typeof MontresHommeRoute
  '/panier': typeof PanierRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/collections/coffrets-cadeaux': typeof CollectionsCoffretsCadeauxRoute
  '/montres/$slug': typeof MontresSlugRoute
  '/montres/': typeof MontresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions-generales-vente': typeof ConditionsGeneralesVenteRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/montres-connectees': typeof MontresConnecteesRoute
  '/montres-couple': typeof MontresCoupleRoute
  '/montres-enfant': typeof MontresEnfantRoute
  '/montres-femme': typeof MontresFemmeRoute
  '/montres-homme': typeof MontresHommeRoute
  '/panier': typeof PanierRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/collections/coffrets-cadeaux': typeof CollectionsCoffretsCadeauxRoute
  '/montres/$slug': typeof MontresSlugRoute
  '/montres': typeof MontresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conditions-generales-vente': typeof ConditionsGeneralesVenteRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/montres-connectees': typeof MontresConnecteesRoute
  '/montres-couple': typeof MontresCoupleRoute
  '/montres-enfant': typeof MontresEnfantRoute
  '/montres-femme': typeof MontresFemmeRoute
  '/montres-homme': typeof MontresHommeRoute
  '/panier': typeof PanierRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/collections/coffrets-cadeaux': typeof CollectionsCoffretsCadeauxRoute
  '/montres/$slug': typeof MontresSlugRoute
  '/montres/': typeof MontresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conditions-generales-vente'
    | '/contact'
    | '/favoris'
    | '/montres-connectees'
    | '/montres-couple'
    | '/montres-enfant'
    | '/montres-femme'
    | '/montres-homme'
    | '/panier'
    | '/suivi-commande'
    | '/collections/coffrets-cadeaux'
    | '/montres/$slug'
    | '/montres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conditions-generales-vente'
    | '/contact'
    | '/favoris'
    | '/montres-connectees'
    | '/montres-couple'
    | '/montres-enfant'
    | '/montres-femme'
    | '/montres-homme'
    | '/panier'
    | '/suivi-commande'
    | '/collections/coffrets-cadeaux'
    | '/montres/$slug'
    | '/montres'
  id:
    | '__root__'
    | '/'
    | '/conditions-generales-vente'
    | '/contact'
    | '/favoris'
    | '/montres-connectees'
    | '/montres-couple'
    | '/montres-enfant'
    | '/montres-femme'
    | '/montres-homme'
    | '/panier'
    | '/suivi-commande'
    | '/collections/coffrets-cadeaux'
    | '/montres/$slug'
    | '/montres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionsGeneralesVenteRoute: typeof ConditionsGeneralesVenteRoute
  ContactRoute: typeof ContactRoute
  FavorisRoute: typeof FavorisRoute
  MontresConnecteesRoute: typeof MontresConnecteesRoute
  MontresCoupleRoute: typeof MontresCoupleRoute
  MontresEnfantRoute: typeof MontresEnfantRoute
  MontresFemmeRoute: typeof MontresFemmeRoute
  MontresHommeRoute: typeof MontresHommeRoute
  PanierRoute: typeof PanierRoute
  SuiviCommandeRoute: typeof SuiviCommandeRoute
  CollectionsCoffretsCadeauxRoute: typeof CollectionsCoffretsCadeauxRoute
  MontresSlugRoute: typeof MontresSlugRoute
  MontresIndexRoute: typeof MontresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suivi-commande': {
      id: '/suivi-commande'
      path: '/suivi-commande'
      fullPath: '/suivi-commande'
      preLoaderRoute: typeof SuiviCommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres-homme': {
      id: '/montres-homme'
      path: '/montres-homme'
      fullPath: '/montres-homme'
      preLoaderRoute: typeof MontresHommeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres-femme': {
      id: '/montres-femme'
      path: '/montres-femme'
      fullPath: '/montres-femme'
      preLoaderRoute: typeof MontresFemmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres-enfant': {
      id: '/montres-enfant'
      path: '/montres-enfant'
      fullPath: '/montres-enfant'
      preLoaderRoute: typeof MontresEnfantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres-couple': {
      id: '/montres-couple'
      path: '/montres-couple'
      fullPath: '/montres-couple'
      preLoaderRoute: typeof MontresCoupleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres-connectees': {
      id: '/montres-connectees'
      path: '/montres-connectees'
      fullPath: '/montres-connectees'
      preLoaderRoute: typeof MontresConnecteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales-vente': {
      id: '/conditions-generales-vente'
      path: '/conditions-generales-vente'
      fullPath: '/conditions-generales-vente'
      preLoaderRoute: typeof ConditionsGeneralesVenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres/': {
      id: '/montres/'
      path: '/montres'
      fullPath: '/montres/'
      preLoaderRoute: typeof MontresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montres/$slug': {
      id: '/montres/$slug'
      path: '/montres/$slug'
      fullPath: '/montres/$slug'
      preLoaderRoute: typeof MontresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/coffrets-cadeaux': {
      id: '/collections/coffrets-cadeaux'
      path: '/collections/coffrets-cadeaux'
      fullPath: '/collections/coffrets-cadeaux'
      preLoaderRoute: typeof CollectionsCoffretsCadeauxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionsGeneralesVenteRoute: ConditionsGeneralesVenteRoute,
  ContactRoute: ContactRoute,
  FavorisRoute: FavorisRoute,
  MontresConnecteesRoute: MontresConnecteesRoute,
  MontresCoupleRoute: MontresCoupleRoute,
  MontresEnfantRoute: MontresEnfantRoute,
  MontresFemmeRoute: MontresFemmeRoute,
  MontresHommeRoute: MontresHommeRoute,
  PanierRoute: PanierRoute,
  SuiviCommandeRoute: SuiviCommandeRoute,
  CollectionsCoffretsCadeauxRoute: CollectionsCoffretsCadeauxRoute,
  MontresSlugRoute: MontresSlugRoute,
  MontresIndexRoute: MontresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
